#!/usr/bin/env bash

# Add environment variables, that are relevant specifically for this machine, here

# Envi Feature Controls - Set to true/false to enable/disable features
export SSH_AGENT_ENABLED=true
export POWERLEVEL10K_ENABLED=true
export TMUX_ENABLED=false
export TMUX_SHOW_HELP=false

export "PATH=$HOME/.local/bin:\
/usr/local/mysql/bin:\
/opt/local/bin:\
/opt/local/sbin:\
/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:\
$HOME/.pyenv/shims:\
/Library/TeX/texbin:\
/usr/local/MacGPG2/bin:\
/usr/games: \
$HOME/.vimpkg/bin:\
$PATH"

