#!/usr/bin/env bash

# Add environment variables, that are relevant specifically for this machine, here

export "PATH=~/.local/bin:\
/usr/local/mysql/bin:\
/opt/local/bin:\
/opt/local/sbin:\
/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:\
~/.pyenv/shims:\
/Library/TeX/texbin:\
/usr/local/MacGPG2/bin:\
/usr/games: \
~/.vimpkg/bin:\
$PATH"

